apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: standard-service
  managed-by: argocd

images:
  - name: app-image
    newTag: v1.0.0
